### ISSUE TITLE
Dockerfile does not build Frontend & build does not work out of the box

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/starter-kit_app_nodejs#18]
```
###############################################################################
###	Frontend
###############################################################################
RUN mkdir -p /app/frontend
WORKDIR /app/frontend

COPY frontend ./
# RUN npm install
# RUN npm run build
```

the install for the frontend and backend is commented out.

If I enable them; the build does not work on 
`FROM node:10.15.0-alpine`

if I switch this to 
`node:carbon` or `node:dubnium`

The FE builds without a problem.

Maybe the FE build requires some extra dependencies which are not installed by default on alpine?

**Comment by TriangleJuice** [comment]
The frontend that's included with the package doesn't have to be built, i.e. it's a static `index.html` file. Only when you replace it with an Angular or React app, these lines have to be enabled. Ok to close this issue?
