### ISSUE TITLE
Potential pitfall: sessionStore is in memory by default

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/starter-kit_app_nodejs#21]
With this starter kit, the default memory store is in memory (not mongo, redis, pg...)
This is not a problem for local development.

But each application should be able to scale to more than one instance, This causes unexpected behavior when a memory store is used.

Maybe this should be changed in the CLI-tool? (cc: @TriangleJuice @vademo)

**Comment by vademo** [comment]
The biggest issue with in-memory data in the starter-kit will be the express-session implementation.

Using the default in-memory configuration of the package is ideal for local development and seems like a good place to start (After all it's a starter-kit and not an app generator). 

For production purposes sessions should be shared across nodes (OpenShift will send all request from the same client to the same instance. But during a release session-data will be lost).

Looking at the package I see 50+ implementations available for using all kinds of  datastores on the express-session package (https://github.com/expressjs/session#compatible-session-stores). 

It's going to be a lot of work to support all options in the generator & maintaining this.
Making predefined selection could be an option if we want to set a standard way of handling sessions-data. However I would prefer giving the developer the freedom & responsibility to choose the best option for the service / app being created.

I would opt to add this to the documentation of the starter-kit. Not to enforce a preferred way or maintain every possible option.

Open to other opinions 😉

**Comment by stefanpante** [comment]
Adding this to the documentation is viable solution.
